### ISSUE TITLE
Cannot Build on OS X

### ISSUE THREAD

**Issue by ysimonson** [boggle/gonewrong#2]
I get the following error:

   gonewrong.go:6:15: error: u.h: No such file or directory

**Comment by boggle** [comment]
This stuff is deprecated. I haven't tried to build this in a while, guess some header file from the cgo toolchain is not found. I'll post here if I come round to looking at it.

**Comment by stapelberg** [comment]
My pull request fixes this: https://github.com/boggle/gonewrong/pull/3
